// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-11-04 17:32:45.497441 +0800 CST m=+1.155820754

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/stock/get": {
            "post": {
                "description": "获取货品在特定仓库中的库存信息",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取货品在特定仓库中的库存信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "货品编码",
                        "name": "skuId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商户仓库编号",
                        "name": "storageId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.SkuStock"
                        }
                    }
                }
            }
        },
        "/stock/inout": {
            "post": {
                "description": "货品入库/出库接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "货品入库/出库接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "货品编码",
                        "name": "skuId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "入库/出库的货品单位",
                        "name": "unit",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "入库/出库的货品数量",
                        "name": "number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商户仓库编号",
                        "name": "storageId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "本次入库的货品强制设定加权均价，不传时由系统计算",
                        "name": "cost",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "本次入库的货品进货价",
                        "name": "price",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.SkuStock"
                        }
                    }
                }
            }
        },
        "/stock/list": {
            "post": {
                "description": "列出商品/货品的库存",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "列出商品/货品的库存接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "货品编码",
                        "name": "skuId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键字，从商品名称中查询",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商户仓库编号",
                        "name": "storageId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品编号",
                        "name": "productId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "分页页号参数，第几页，若要分页，页号\u003e=1，否则为0",
                        "name": "page",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "分页大小参数",
                        "name": "size",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.SkuStock"
                        }
                    }
                }
            }
        },
        "/stock/num": {
            "post": {
                "description": "获取指定货品/商品的库存量",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取指定货品/商品的库存量",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "货品自定义编号",
                        "name": "skuId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商户仓库编号",
                        "name": "storageId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品编号",
                        "name": "productId",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/common.Result"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.Result": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                },
                "page": {
                    "type": "ResultPage"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "model.SkuStock": {
            "type": "object",
            "properties": {
                "base_unit": {
                    "type": "string"
                },
                "cost_price": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "last_price": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "shop_id": {
                    "type": "string"
                },
                "sku_id": {
                    "type": "string"
                },
                "stocks": {
                    "type": "integer"
                },
                "storage_id": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0(jxc-stock)",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
