// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-11-04 17:32:03.743111 +0800 CST m=+4.731545595

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/category/del": {
            "post": {
                "description": "删除商品分类接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "删除商品分类接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品分类记录号",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/common.Result"
                        }
                    }
                }
            }
        },
        "/category/down": {
            "post": {
                "description": "下移商品分类接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "下移商品分类接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品分类记录号",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductCategory"
                        }
                    }
                }
            }
        },
        "/category/get": {
            "post": {
                "description": "查询商品分类接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "查询商品分类接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品分类记录号",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品分类自定义编号",
                        "name": "categoryId",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductCategory"
                        }
                    }
                }
            }
        },
        "/category/list": {
            "post": {
                "description": "按菜单层级方式或路径方式列出商品分类",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "列出商品的所有商品分类接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品分类号，按编号查完整分类路径",
                        "name": "categoryId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "上级分类编号",
                        "name": "parent",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "分类层级",
                        "name": "level",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductCategory"
                        }
                    }
                }
            }
        },
        "/category/save": {
            "post": {
                "description": "保存商品分类接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "保存商品分类接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账户",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品分类名称",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品分类自定义编号,默认自动生成",
                        "name": "categoryId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "上级分类编号，第一级无上级分类的填0",
                        "name": "parent",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "商品分类层级，从第1级向下",
                        "name": "level",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductCategory"
                        }
                    }
                }
            }
        },
        "/category/up": {
            "post": {
                "description": "上移商品分类接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "上移商品分类接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品分类记录号",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductCategory"
                        }
                    }
                }
            }
        },
        "/category/update": {
            "post": {
                "description": "修改商品分类接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "修改商品分类接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品分类编号",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品分类名称",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品分类自定义编号",
                        "name": "categoryId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "上级分类编号，第一级无上级分类的填0",
                        "name": "parent",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "商品分类层级，从第1级向下",
                        "name": "level",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductCategory"
                        }
                    }
                }
            }
        },
        "/product/del": {
            "post": {
                "description": "删除商品信息接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "删除商品信息接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品编号",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/common.Result"
                        }
                    }
                }
            }
        },
        "/product/get": {
            "post": {
                "description": "查询商品信息接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "查询商品信息接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品记录号",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品自定义编号",
                        "name": "productId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品条码",
                        "name": "barCode",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductInfo"
                        }
                    }
                }
            }
        },
        "/product/list": {
            "post": {
                "description": "列出商品信息接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "列出商品信息接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "模糊搜索关键字：商品名称/全拼(小写)/拼音首字母(大写)",
                        "name": "keyword",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品分类编号",
                        "name": "categoryId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "分页页号参数，第几页，若要分页，页号\u003e=1，否则为0",
                        "name": "page",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "分页大小参数",
                        "name": "size",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductInfo"
                        }
                    }
                }
            }
        },
        "/product/save": {
            "post": {
                "description": "保存商品信息接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "保存商品信息接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品分类编号",
                        "name": "categoryId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品名称",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品自定义编号，默认系统自动生成",
                        "name": "productId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品条码",
                        "name": "barCode",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品基础单位，最小单位",
                        "name": "baseUnit",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductInfo"
                        }
                    }
                }
            }
        },
        "/product/update": {
            "post": {
                "description": "修改商品信息接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "修改商品信息接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品编号",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品分类编码",
                        "name": "categoryId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品自定义编号",
                        "name": "productId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品名称",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品基础单位，最小单位",
                        "name": "baseUnit",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品条码",
                        "name": "barCode",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductInfo"
                        }
                    }
                }
            }
        },
        "/sku/del": {
            "post": {
                "description": "删除货品接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "删除货品接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "货品全局编码",
                        "name": "skuGuid",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "货品自定义编码",
                        "name": "skuId",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/common.Result"
                        }
                    }
                }
            }
        },
        "/sku/down": {
            "post": {
                "description": "下移货品接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "下移货品接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "货品全局编码",
                        "name": "skuGuid",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSku"
                        }
                    }
                }
            }
        },
        "/sku/get": {
            "post": {
                "description": "查询货品接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "查询货品接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "货品全局编码",
                        "name": "skuGuid",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "货品自定义编码",
                        "name": "skuId",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSku"
                        }
                    }
                }
            }
        },
        "/sku/list": {
            "post": {
                "description": "按自由组合方式与关键字模糊查询方式列出货品",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "列出商品的所有货品接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "搜索关键字，从商品名称、全拼、拼音首字母",
                        "name": "keyword",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品规格，JSON格式",
                        "name": "specs",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "商品分类编号",
                        "name": "categoryId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "商品编号",
                        "name": "productId",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "货品上架状态",
                        "name": "status",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "分页页号参数，第几页，若要分页，页号\u003e=1，否则为0",
                        "name": "page",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "分页大小参数",
                        "name": "size",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSku"
                        }
                    }
                }
            }
        },
        "/sku/save": {
            "post": {
                "description": "保存货品接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "保存货品接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "商品编号",
                        "name": "productId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "货品规格，JSON格式，{\u003c规格名\u003e:\u003c格式值\u003e}",
                        "name": "specs",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "货品自定义编码，不传则自动随机生成",
                        "name": "skuId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "货品全局唯一编码，默认不传，随机生成32位码",
                        "name": "skuGuid",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "货品名称，默认为商品名+规格值",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "货品报价表，JSON格式",
                        "name": "prices",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSku"
                        }
                    }
                }
            }
        },
        "/sku/up": {
            "post": {
                "description": "上移货品接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "上移货品接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "货品全局编码",
                        "name": "skuGuid",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSku"
                        }
                    }
                }
            }
        },
        "/sku/update": {
            "post": {
                "description": "修改货品接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "修改货品接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "货品全局唯一编码",
                        "name": "skuGuid",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "货品自定义编码，不传则自动随机生成",
                        "name": "skuId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品名称",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "货品名称",
                        "name": "skuName",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "货品条码",
                        "name": "barCode",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "货品规格，JSON格式，{\u003c规格名\u003e:\u003c格式值\u003e}",
                        "name": "specs",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "货品报价表，JSON格式",
                        "name": "prices",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "货品状态，0-禁售 1-可售",
                        "name": "status",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSku"
                        }
                    }
                }
            }
        },
        "/specs/add": {
            "post": {
                "description": "添加商品规格值接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "添加商品规格值接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品规格编号",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "单个商品规格值",
                        "name": "value",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSpecs"
                        }
                    }
                }
            }
        },
        "/specs/del": {
            "post": {
                "description": "删除商品规格指标接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "删除商品规格指标接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品规格编号",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/common.Result"
                        }
                    }
                }
            }
        },
        "/specs/get": {
            "post": {
                "description": "查询商品的规格指标接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "查询商品的规格指标接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品规格编号",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品编号",
                        "name": "productId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品规格名",
                        "name": "specs",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSpecs"
                        }
                    }
                }
            }
        },
        "/specs/list": {
            "post": {
                "description": "列出商品的所有规格指标接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "列出商品的所有规格指标接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品自定义编码",
                        "name": "productId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSpecs"
                        }
                    }
                }
            }
        },
        "/specs/remove": {
            "post": {
                "description": "移除商品规格值接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "移除商品规格值接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品规格编号",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "要移除的单个商品规格值",
                        "name": "value",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSpecs"
                        }
                    }
                }
            }
        },
        "/specs/save": {
            "post": {
                "description": "保存规格指标接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "保存规格指标接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品编号",
                        "name": "productId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品规格名",
                        "name": "specs",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品规格值列表，JSON数组格式",
                        "name": "values",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSpecs"
                        }
                    }
                }
            }
        },
        "/specs/update": {
            "post": {
                "description": "修改商品规格指标接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "修改商品规格指标接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品规格编号",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品编号",
                        "name": "productId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品规格名",
                        "name": "specs",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品规格值列表，JSON数组格式",
                        "name": "values",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSpecs"
                        }
                    }
                }
            }
        },
        "/supplier/del": {
            "post": {
                "description": "删除商品供应商接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "删除商品供应商接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品供应商编号",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/common.Result"
                        }
                    }
                }
            }
        },
        "/supplier/get": {
            "post": {
                "description": "查询商品的供应商接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "查询商品的供应商接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品供应商记录号",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品编号",
                        "name": "productId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品供应商账号",
                        "name": "supplierId",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSupplier"
                        }
                    }
                }
            }
        },
        "/supplier/list": {
            "post": {
                "description": "列出商品的所有供应商接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "列出商品的所有供应商接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品编号",
                        "name": "productId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSupplier"
                        }
                    }
                }
            }
        },
        "/supplier/save": {
            "post": {
                "description": "保存供应商接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "保存供应商接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商品编号",
                        "name": "productId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品供应商账号",
                        "name": "supplierId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品供应商名称",
                        "name": "supplierName",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSupplier"
                        }
                    }
                }
            }
        },
        "/supplier/update": {
            "post": {
                "description": "修改商品供应商接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "修改商品供应商接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品供应商id",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品编号",
                        "name": "productId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品供应商账号",
                        "name": "supplierId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商品供应商名称",
                        "name": "supplierName",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductSupplier"
                        }
                    }
                }
            }
        },
        "/unit/del": {
            "post": {
                "description": "删除商品单位换算规则接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "删除商品单位换算规则接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品单位换算编号",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/common.Result"
                        }
                    }
                }
            }
        },
        "/unit/get": {
            "post": {
                "description": "查询商品的单位换算规则接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "查询商品的单位换算规则接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品编号",
                        "name": "productId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品辅助单位，较大的单位",
                        "name": "unit",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品基础单位，最小单位",
                        "name": "baseUnit",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductUnit"
                        }
                    }
                }
            }
        },
        "/unit/list": {
            "post": {
                "description": "列出商品的所有单位换算规则接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "列出商品的所有单位换算规则接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品编号",
                        "name": "productId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductUnit"
                        }
                    }
                }
            }
        },
        "/unit/save": {
            "post": {
                "description": "保存单位换算规则接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "保存单位换算规则接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品编号",
                        "name": "productId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "商品单位换算比例值: 1辅助单位=scale个基础单位",
                        "name": "scale",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品辅助单位，较大的单位",
                        "name": "unit",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品基础单位，最小单位",
                        "name": "baseUnit",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductUnit"
                        }
                    }
                }
            }
        },
        "/unit/update": {
            "post": {
                "description": "修改商品单位换算规则接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "修改商品单位换算规则接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户账号",
                        "name": "shopId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品编号",
                        "name": "productId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "商品单位换算比例值: 1辅助单位=scale个基础单位",
                        "name": "scale",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品辅助单位，较大的单位",
                        "name": "unit",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商品基础单位，最小单位",
                        "name": "baseUnit",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":1,\u003cbr\u003e\\\"msg\\\":\\\"成功\\\",\u003cbr\u003e\\\"data\\\":{},\u003cbr\u003e\\\"page\\\":null}",
                        "schema": {
                            "$ref": "#/definitions/model.ProductUnit"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.Result": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                },
                "page": {
                    "type": "ResultPage"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "model.ProductCategory": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                },
                "shop_id": {
                    "type": "string"
                },
                "sort_number": {
                    "type": "integer"
                }
            }
        },
        "model.ProductInfo": {
            "type": "object",
            "properties": {
                "bar_code": {
                    "type": "string"
                },
                "base_unit": {
                    "type": "string"
                },
                "category_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "pinyin_first": {
                    "type": "string"
                },
                "pinyin_full": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "shop_id": {
                    "type": "string"
                }
            }
        },
        "model.ProductSku": {
            "type": "object",
            "properties": {
                "barCode": {
                    "type": "string"
                },
                "baseUnit": {
                    "type": "string"
                },
                "categoryId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pinyinFirst": {
                    "type": "string"
                },
                "pinyinFull": {
                    "type": "string"
                },
                "priceList": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/string"
                    }
                },
                "productId": {
                    "type": "string"
                },
                "shopId": {
                    "type": "string"
                },
                "sku": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/string"
                    }
                },
                "skuGuid": {
                    "type": "string"
                },
                "skuId": {
                    "type": "string"
                },
                "skuName": {
                    "type": "string"
                },
                "sortNumber": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "model.ProductSpecs": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "shop_id": {
                    "type": "string"
                },
                "values": {
                    "type": "string"
                }
            }
        },
        "model.ProductSupplier": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "string"
                },
                "shop_id": {
                    "type": "string"
                },
                "supplier_id": {
                    "type": "string"
                },
                "supplier_name": {
                    "type": "string"
                }
            }
        },
        "model.ProductUnit": {
            "type": "object",
            "properties": {
                "base_unit": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "string"
                },
                "scale": {
                    "type": "integer"
                },
                "shop_id": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0(jxc-product)",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
