definitions:
  model.DeliveryType:
    properties:
      id:
        type: integer
      shop_id:
        type: string
      type:
        type: string
    type: object
  model.EntryType:
    properties:
      id:
        type: integer
      shop_id:
        type: string
      type:
        type: string
    type: object
  model.ShopStorage:
    properties:
      id:
        type: integer
      name:
        type: string
      remark:
        type: string
      shop_id:
        type: string
      sort_number:
        type: integer
      storage_id:
        type: string
    type: object
  model.StockDelivery:
    properties:
      cost:
        type: integer
      customer_id:
        type: string
      customer_name:
        type: string
      delivery_no:
        type: string
      delivery_time:
        type: string
      id:
        type: integer
      multi_storage:
        type: string
      number:
        type: integer
      operator:
        type: string
      order_no:
        type: string
      price:
        type: integer
      remark:
        type: string
      shop_id:
        type: string
      sku_id:
        type: string
      storage_id:
        type: string
      type:
        type: string
      unit:
        type: string
    type: object
  model.Unit:
    properties:
      id:
        type: integer
      shop_id:
        type: string
      unit:
        type: string
    type: object
info:
  contact: {}
  license: {}
  version: 1.0.0(jxc-base)
paths:
  /deliverytype/del:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 删除出库类型接口
      parameters:
      - description: 出库类型编号
        in: formData
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.DeliveryType'
      summary: 删除出库类型接口
  /deliverytype/list:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 列出商户的所有出库类型接口
      parameters:
      - description: 商户号
        in: formData
        name: shopId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.DeliveryType'
      summary: 列出商户的所有出库类型接口
  /deliverytype/save:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 保存出库类型接口
      parameters:
      - description: 商户号
        in: formData
        name: shopId
        type: string
      - description: 出库类型
        in: formData
        name: deliveryType
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.DeliveryType'
      summary: 保存出库类型接口
  /deliverytype/update:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 更新出库类型接口
      parameters:
      - description: 出库类型编号
        in: formData
        name: id
        required: true
        type: integer
      - description: 出库类型
        in: formData
        name: deliveryType
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.DeliveryType'
      summary: 更新出库类型接口
  /entrytype/del:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 删除入库类型接口
      parameters:
      - description: 入库类型编号
        in: formData
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.EntryType'
      summary: 删除入库类型接口
  /entrytype/list:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 列出商户的所有入库类型接口
      parameters:
      - description: 商户号
        in: formData
        name: shopId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.EntryType'
      summary: 列出商户的所有入库类型接口
  /entrytype/save:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 保存入库类型接口
      parameters:
      - description: 商户号
        in: formData
        name: shopId
        type: string
      - description: 入库类型
        in: formData
        name: entryType
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.EntryType'
      summary: 保存入库类型接口
  /entrytype/update:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 更新入库类型接口
      parameters:
      - description: 入库类型编号
        in: formData
        name: id
        required: true
        type: integer
      - description: 入库类型
        in: formData
        name: entryType
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.EntryType'
      summary: 更新入库类型接口
  /storage/del:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 删除仓库接口
      parameters:
      - description: 商户账号
        in: formData
        name: shopId
        required: true
        type: string
      - description: 自定义仓库编码
        in: formData
        name: storageId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.ShopStorage'
      summary: 删除仓库接口
  /storage/down:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 仓库顺序号向下移一个位置接口
      parameters:
      - description: 商户号
        in: formData
        name: shopId
        required: true
        type: string
      - description: 仓库编号
        in: formData
        name: storageId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.ShopStorage'
      summary: 仓库顺序号向下移一个位置接口
  /storage/get:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 获取仓库接口
      parameters:
      - description: 商户号
        in: formData
        name: shopId
        required: true
        type: string
      - description: 仓库编号
        in: formData
        name: storageId
        type: string
      - description: 仓库名称
        in: formData
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.ShopStorage'
      summary: 获取仓库接口
  /storage/last:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 获取指定仓库最后修改信息接口
      parameters:
      - description: 商户账号
        in: formData
        name: shopId
        required: true
        type: string
      - description: 仓库编号
        in: formData
        name: storageId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.StockDelivery'
      summary: 获取指定仓库最后修改信息接口
  /storage/list:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 列出商户的所有仓库接口
      parameters:
      - description: 商户号
        in: formData
        name: shopId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.ShopStorage'
      summary: 列出商户的所有仓库接口
  /storage/save:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 保存仓库接口
      parameters:
      - description: 商户账号
        in: formData
        name: shopId
        required: true
        type: string
      - description: 仓库名称
        in: formData
        name: name
        required: true
        type: string
      - description: 自定义仓库编码，不传则自动生成
        in: formData
        name: storageId
        type: string
      - description: 备注
        in: formData
        name: remark
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.ShopStorage'
      summary: 保存仓库接口
  /storage/up:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 仓库顺序号向上移一个位置接口
      parameters:
      - description: 商户号
        in: formData
        name: shopId
        required: true
        type: string
      - description: 仓库编号
        in: formData
        name: storageId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.ShopStorage'
      summary: 仓库顺序号向上移一个位置接口
  /storage/update:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 更新仓库接口
      parameters:
      - description: 仓库记录序列号，若不传时则不可修改自定义仓库编码
        in: formData
        name: id
        type: integer
      - description: 商户账号
        in: formData
        name: shopId
        type: string
      - description: 自定义仓库编码
        in: formData
        name: storageId
        type: string
      - description: 仓库名称
        in: formData
        name: name
        type: string
      - description: 备注
        in: formData
        name: remark
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.ShopStorage'
      summary: 更新仓库接口
  /unit/del:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 删除单位接口
      parameters:
      - description: 单位编号
        in: formData
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.Unit'
      summary: 删除单位接口
  /unit/list:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 列出商户的所有单位接口
      parameters:
      - description: 商户号
        in: formData
        name: shopId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.Unit'
      summary: 列出商户的所有单位接口
  /unit/save:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 保存单位接口
      parameters:
      - description: 商户号
        in: formData
        name: shopId
        type: string
      - description: 单位
        in: formData
        name: unit
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.Unit'
      summary: 保存单位接口
  /unit/update:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 更新单位接口
      parameters:
      - description: 单位编号
        in: formData
        name: id
        required: true
        type: integer
      - description: 单位
        in: formData
        name: unit
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{\"status\":1,<br>\"msg\":\"成功\",<br>\"data\":{},<br>\"page\":null}'
          schema:
            $ref: '#/definitions/model.Unit'
      summary: 更新单位接口
swagger: "2.0"
